# Generated by Django 4.2.10 on 2024-03-07 08:53

from django.db import migrations, models
import recipebook.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=4000)),
                ('ingredients', models.TextField(max_length=10000)),
                ('image', models.FileField(null=True, upload_to=recipebook.models.user_directory_path, verbose_name='')),
            ],
        ),
    ]
